version: "3.7"

services:
    backend:
        container_name: flask
        build: .
        environment:
            CHOKIDAR_USEPOLLING: "true"
        command: python manage.py run -h 0.0.0.0
        ports:
            - 1709:5000
        env_file:
            - .env.dev
        extra_hosts:
            - "host.docker.internal:host-gateway"
        volumes:
            - .:/usr/src/app
#    frontend:
#        container_name: frontend
#        image: node:13.12.0-alpine
#        working_dir: /app/frontend
#        environment:
#            CHOKIDAR_USEPOLLING: "true"
#        volumes:
#            - ./frontend/:/app/frontend
#        command: >
#            sh -c "npm start"
##            sh -c "npm install && npm start"
#        ports:
#            - 3000:3000

        

